name = "celso-io"
type = "webpack"

[env.staging]
workers_dev = true

[env.production]
workers_dev = false
route = "celso.io/*"

[dev]
port=9000
ip="127.0.0.1"

[site]
bucket = "./_site"
entry-point = "workers-site"
